---
- name: Set Up Target Server for L2DSR
  hosts: centos
  become: yes
  become_user: root
  become_method: sudo
  become_flags: "-i"
  gather_facts: yes
  vars_files:
    - /home/vagrant/loopback/l4_var.yml
  

  tasks:
  - name: L2DSR For CentOS
    include_tasks: CentOS_loopbackForL4.yml
    when: ansible_distribution == 'CentOS'
  
  - name: L2DSR For Ubuntu
    include_tasks: Ubuntu_loopbackForL4.yml
    when: ansible_distribution == 'Ubuntu'